name: Terraform Destroy Pipeline

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Run terraform init
        run: terraform -chdir=terraform init

      - name: Run terraform destroy
        run: |
          terraform -chdir=terraform destroy -auto-approve \
            -var="certificate_arn=${{ secrets.CERTIFICATE_ARN }}" \
            -var="container_image=${{ secrets.CONTAINER_IMAGE }}" \
            -var="execution_role_arn=${{ secrets.EXECUTION_ROLE_ARN }}"
